version: '3.8'
services:
  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./codebase/backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env      # .env en la raíz del proyecto
volumes:
  mongo-data:
